import { PUBLIC_ENV_MODE, PUBLIC_API_TEST_URL, PUBLIC_API_MAIN_URL } from '$env/static/public';

export const API_END_POINT =
	PUBLIC_ENV_MODE === 'DEVELOPMENT' ? PUBLIC_API_TEST_URL : PUBLIC_API_MAIN_URL;
